name: test deploy

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: benjlevesque/short-sha@v1.2
        id: image_tag
        with:
          length: 7

      - name: deploy application to kubernetes
        uses: 'deliverybot/helm@v1.5.0'
        with:
          helm: helm3
          release: test-keycloak
          namespace: default
          chart: charts/keycloak
          version: 1.2.3
          chartVersion: 4.5.6
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}
